spec-version: 0.36.0
name: simdutf

copyright: (c) 2023 Simon Hengel
author: Simon Hengel <sol@typeful.net>

ghc-options: -Wall

extra-source-files:
  - vendor/simdutf.h
  - vendor/LICENSE-MIT

dependencies:
  base: 4.*

library:
  source-dirs: src
  include-dirs: vendor
  dependencies:
    system-cxx-std-lib: 1.*
  cxx-options: -std=c++17
  cxx-sources:
    - vendor/simdutf.cpp
    - cbits/utf8.cpp

tests:
  spec:
    build-tools: hspec-discover
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - simdutf
      - hspec == 2.*
